version: "3.2"
services:
  reverse-proxy:
    build: "./reverseProxy"
    ports:
      - "81:80"
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - server
      - app
  app:
    build: "./app"
    ports:
      - "3000:3000"
    expose:
      - 3000
    labels:
      - "traefik.backend=app"
      - "traefik.frontend.rule=PathPrefix:/dist,/sockjs-node"
      - "traefik.frontend.priority=2"
      - "traefik.enable=true"
      - "traefik.port=3000"
  server:
    build: "./server"
    command: npm run server
    expose:
      - 3001
    labels:
      - "traefik.backend=server"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=1"
      - "traefik.enable=true"
      - "traefik.port=3001"
    links:
      - db
  db:
    image: postgres
    expose:
      - 5432
